
# Adapted for this jhudsl repository by Candace Savonen Aug 2021

name: Update docs

# Triggers the workflow on pull requests for the master branch OR can be manually triggered
on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      # Checks-out the code from this repo
      - name: Checkout code from repo
        uses: actions/checkout@v2

      # Install packages
      - name: Install packages
        run: |
          devtools::load_all()

      # Run main function
      - name: Run build site
        run: |
          gitHelpeR::retrieve_org_chapters(org_name = "jhudsl", output_file = "jhudsl_chapter_info.tsv")
