
# Candace Savonen Dec 2021

name: Update Googlesheet

# Triggers the workflow on pull requests for the main branch OR can be manually triggered
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: rocker/tidyverse:4.0.0

    steps:
      # Checks-out the code from this repo
      - name: Checkout code from repo
        uses: actions/checkout@v2

      # Run main function
      - name: Run build site
        run: |
          Rscript -e "install.packages(c('gitcreds','htm2txt','textrank','udpipe'))"
          Rscript --vanilla "update-googlesheet.R"
