
# Candace Savonen Dec 2021

name: Update Googlesheet

# Triggers the workflow on pull requests for the main branch OR can be manually triggered
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: jhudsl/course-library

    steps:
      # Checks-out the code from this repo
      - name: Checkout code from repo
        uses: actions/checkout@v3

      # Get auth tokens
      - name: Get token
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo ${{ secrets.GH_PAT }} > git_token.txt

          curl https://${GH_PAT}@raw.githubusercontent.com/cansavvy/secret-secrets/main/googlesheets-secret.json > googlesheets-secret.json

          mkdir .secrets
          cd .secrets
          curl https://${GH_PAT}@raw.githubusercontent.com/cansavvy/secret-secrets/main/7334fcb1e7635f8da2b81898d2220edf_cansav09%40gmail.com > 7334fcb1e7635f8da2b81898d2220edf_cansav0@gmail.com

      # Run main function
      - name: Run build update googlesheet
        run: |
          Rscript update-googlesheet.R
