
# Candace Savonen Dec 2021

name: Update Googlesheet

# Triggers the workflow on pull requests for the main branch OR can be manually triggered
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: jhudsl/course-library

    steps:
      # Checks-out the code from this repo
      - name: Checkout code from repo
        uses: actions/checkout@v2

      # Get GITHUB PAT
      - name: Get token
        run: echo ${{ secrets.GH_PAT }} > git_token.txt

      # Run main function
      - name: Run build site
        run: |
          Rscript --vanilla "update-googlesheet.R"
