
# Candace Savonen Dec 2021

name: Update Googlesheet

# Triggers the workflow on pull requests for the main branch OR can be manually triggered
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  update:
    runs-on: ubuntu-latest
    container:
      image: jhudsl/course-library

    steps:
      # Checks-out the code from this repo
      - name: Checkout code from repo
        uses: actions/checkout@v2

      # Get auth tokens
      - name: Get token
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          echo ${{ secrets.GH_PAT }} > git_token.txt

          git config user.email "cansav09@gmail.com"
          git config user.name "cansavvy"

          curl https://${GH_PAT}@raw.githubusercontent.com/cansavvy/secret-secrets/main/token.rds > token.rds

      # Run main function
      - name: Run build update googlesheet
        run: |
          Rscript update-googlesheet.R
